-- Name overrides for live DB
UPDATE public.teams SET name = 'Fylkir', short_name = 'Fylkir' WHERE api_football_id = 267;
UPDATE public.teams SET name = 'Íþróttabandalag Vestmannaeyja', short_name = 'ÍBV' WHERE api_football_id = 268;
UPDATE public.teams SET name = 'Keflavík', short_name = 'Keflavík' WHERE api_football_id = 269;
UPDATE public.teams SET name = 'Fimleikafélag Hafnarfjarðar', short_name = 'FH' WHERE api_football_id = 270;
UPDATE public.teams SET name = 'Knattspyrnufélag Reykjavíkur', short_name = 'KR' WHERE api_football_id = 271;
UPDATE public.teams SET name = 'Knattspyrnufélag Akureyrar', short_name = 'KA' WHERE api_football_id = 272;
UPDATE public.teams SET name = 'Fjölnir', short_name = 'Fjölnir' WHERE api_football_id = 273;
UPDATE public.teams SET name = 'Valur', short_name = 'Valur' WHERE api_football_id = 274;
UPDATE public.teams SET name = 'Stjarnan', short_name = 'Stjarnan' WHERE api_football_id = 275;
UPDATE public.teams SET name = 'Breiðablik', short_name = 'Breiðablik' WHERE api_football_id = 276;
UPDATE public.teams SET name = 'Grindavík', short_name = 'Grindavík' WHERE api_football_id = 277;
UPDATE public.teams SET name = 'Víkingur Reykjavík', short_name = 'Víkingur R' WHERE api_football_id = 278;
UPDATE public.teams SET name = 'Íþróttabandalag Akraness', short_name = 'ÍA' WHERE api_football_id = 827;
UPDATE public.teams SET name = 'Víkingur Ólafsvík', short_name = 'Víkingur Ó' WHERE api_football_id = 828;
UPDATE public.teams SET name = 'Þróttur Reykjavík', short_name = 'Þróttur R' WHERE api_football_id = 829;
UPDATE public.teams SET name = 'Fjarðabyggð', short_name = 'Fjarðabyggð' WHERE api_football_id = 2112;
UPDATE public.teams SET name = 'Handknattleiksfélag Kópavogs', short_name = 'HK' WHERE api_football_id = 2113;
UPDATE public.teams SET name = 'Leiknir Reykjavík', short_name = 'Leiknir R' WHERE api_football_id = 2114;
UPDATE public.teams SET name = 'Selfoss', short_name = 'Selfoss' WHERE api_football_id = 2115;
UPDATE public.teams SET name = 'Þór Akureyri', short_name = 'Þór' WHERE api_football_id = 2116;
UPDATE public.teams SET name = 'Fram', short_name = 'Fram' WHERE api_football_id = 2117;
UPDATE public.teams SET name = 'Haukar', short_name = 'Haukar' WHERE api_football_id = 2118;
UPDATE public.teams SET name = 'Leiknir Fáskrúðsfirði', short_name = 'Leiknir F' WHERE api_football_id = 2120;
UPDATE public.teams SET name = 'Grótta', short_name = 'Grótta' WHERE api_football_id = 2121;
UPDATE public.teams SET name = 'Íþróttafélag Reykjavíkur', short_name = 'ÍR' WHERE api_football_id = 2122;
UPDATE public.teams SET name = 'Njarðvík', short_name = 'Njarðvík' WHERE api_football_id = 2123;
UPDATE public.teams SET name = 'Magni', short_name = 'Magni' WHERE api_football_id = 2124;
UPDATE public.teams SET name = 'Afturelding', short_name = 'Afturelding' WHERE api_football_id = 3514;
UPDATE public.teams SET name = 'Knattspyrnufélag Fjallabyggðar', short_name = 'KF' WHERE api_football_id = 4162;
UPDATE public.teams SET name = 'Sindri', short_name = 'Sindri' WHERE api_football_id = 4164;
UPDATE public.teams SET name = 'Vestri', short_name = 'Vestri' WHERE api_football_id = 4165;
UPDATE public.teams SET name = 'Völsungur', short_name = 'Völsungur' WHERE api_football_id = 4166;
UPDATE public.teams SET name = 'Ægir', short_name = 'Ægir' WHERE api_football_id = 4167;
UPDATE public.teams SET name = 'Tindastóll', short_name = 'Tindastóll' WHERE api_football_id = 4168;
UPDATE public.teams SET name = 'Víðir', short_name = 'Víðir' WHERE api_football_id = 4169;
UPDATE public.teams SET name = 'Kári', short_name = 'Kári' WHERE api_football_id = 4170;
UPDATE public.teams SET name = 'Þróttur Vogar', short_name = 'Þróttur V' WHERE api_football_id = 4171;
UPDATE public.teams SET name = 'Dalvík/Reynir', short_name = 'Dalvík/Reynir' WHERE api_football_id = 4172;
UPDATE public.teams SET name = 'Knattspyrnufélag Garðabæjar', short_name = 'KFG' WHERE api_football_id = 4173;
UPDATE public.teams SET name = 'Afríka', short_name = 'Afríka' WHERE api_football_id = 6076;
UPDATE public.teams SET name = 'Augnablik', short_name = 'Augnablik' WHERE api_football_id = 6077;
UPDATE public.teams SET name = 'Berserkir', short_name = 'Berserkir' WHERE api_football_id = 6078;
UPDATE public.teams SET name = 'Björninn', short_name = 'Björninn' WHERE api_football_id = 6079;
UPDATE public.teams SET name = 'Einherji', short_name = 'Einherji' WHERE api_football_id = 6080;
UPDATE public.teams SET name = 'Elliði', short_name = 'Elliði' WHERE api_football_id = 6081;
UPDATE public.teams SET name = 'Golfklúbbur Grindavíkur', short_name = 'GG' WHERE api_football_id = 6083;
UPDATE public.teams SET name = 'Hamar', short_name = 'Hamar' WHERE api_football_id = 6084;
UPDATE public.teams SET name = 'Hvíti riddarinn', short_name = 'Hvíti r.' WHERE api_football_id = 6085;
UPDATE public.teams SET name = 'Hörður Ísafjörður', short_name = 'Hörður Í' WHERE api_football_id = 6086;
UPDATE public.teams SET name = 'Höttur/Huginn', short_name = 'Höttur/H' WHERE api_football_id = 6087;
UPDATE public.teams SET name = 'KB', short_name = 'KB' WHERE api_football_id = 6088;
UPDATE public.teams SET name = 'KFR', short_name = 'KFR' WHERE api_football_id = 6089;
UPDATE public.teams SET name = 'KFS', short_name = 'KFS' WHERE api_football_id = 6090;
UPDATE public.teams SET name = 'KH', short_name = 'KH' WHERE api_football_id = 6091;
UPDATE public.teams SET name = 'KM', short_name = 'KM' WHERE api_football_id = 6092;
UPDATE public.teams SET name = 'Kormákur/Hvöt', short_name = 'Kormákur' WHERE api_football_id = 6093;
UPDATE public.teams SET name = 'Kría', short_name = 'Kría' WHERE api_football_id = 6094;
UPDATE public.teams SET name = 'KÁ Hafnarfjörður', short_name = 'KÁ' WHERE api_football_id = 6095;
UPDATE public.teams SET name = 'Kórdrengir', short_name = 'Kórdrengir' WHERE api_football_id = 6097;
UPDATE public.teams SET name = 'Léttir', short_name = 'Léttir' WHERE api_football_id = 6098;
UPDATE public.teams SET name = 'Mídas', short_name = 'Mídas' WHERE api_football_id = 6099;
UPDATE public.teams SET name = 'Nökkvi', short_name = 'Nökkvi' WHERE api_football_id = 6100;
UPDATE public.teams SET name = 'Reynir Sandgerði', short_name = 'Reynir S' WHERE api_football_id = 6101;
UPDATE public.teams SET name = 'SR', short_name = 'SR' WHERE api_football_id = 6102;
UPDATE public.teams SET name = 'Samherjar', short_name = 'Samherjar' WHERE api_football_id = 6103;
UPDATE public.teams SET name = 'Skallagrímur', short_name = 'Skallagrímur' WHERE api_football_id = 6104;
UPDATE public.teams SET name = 'Snæfell', short_name = 'Snæfell' WHERE api_football_id = 6105;
UPDATE public.teams SET name = 'Vatnaliljur', short_name = 'Vatnaliljur' WHERE api_football_id = 6106;
UPDATE public.teams SET name = 'Vængir Júpíters', short_name = 'Vængir J' WHERE api_football_id = 6107;
UPDATE public.teams SET name = 'Álafoss', short_name = 'Álafoss' WHERE api_football_id = 6108;
UPDATE public.teams SET name = 'Álftanes', short_name = 'Álftanes' WHERE api_football_id = 6109;
UPDATE public.teams SET name = 'Árborg', short_name = 'Árborg' WHERE api_football_id = 6110;
UPDATE public.teams SET name = 'Íþróttafélag Hafnarfjarðar', short_name = 'ÍH' WHERE api_football_id = 6112;
UPDATE public.teams SET name = 'Ísbjörninn', short_name = 'Ísbjörninn' WHERE api_football_id = 6113;
UPDATE public.teams SET name = 'Úlfarnir', short_name = 'Úlfarnir' WHERE api_football_id = 6114;
UPDATE public.teams SET name = 'Ýmir', short_name = 'Ýmir' WHERE api_football_id = 6115;
UPDATE public.teams SET name = 'Blix', short_name = 'Blix' WHERE api_football_id = 10116;
UPDATE public.teams SET name = 'KFB', short_name = 'KFB' WHERE api_football_id = 10117;
UPDATE public.teams SET name = 'Skandinavía', short_name = 'Skandinavía' WHERE api_football_id = 10118;
UPDATE public.teams SET name = 'Stokkseyri', short_name = 'Stokkseyri' WHERE api_football_id = 10119;
UPDATE public.teams SET name = 'ÍBU', short_name = 'ÍBU' WHERE api_football_id = 10120;
UPDATE public.teams SET name = 'Gullfálkinn', short_name = 'Gullfálkinn' WHERE api_football_id = 16442;
UPDATE public.teams SET name = 'RB', short_name = 'RB' WHERE api_football_id = 16443;
UPDATE public.teams SET name = 'Reynir Hellissandur', short_name = 'Reynir H' WHERE api_football_id = 16444;
UPDATE public.teams SET name = 'Hamrarnir', short_name = 'Hamrarnir' WHERE api_football_id = 16624;
UPDATE public.teams SET name = 'Fjarðabyggð/Leiknir', short_name = 'Fjarðab./L' WHERE api_football_id = 18366;
UPDATE public.teams SET name = 'Berserkir/Mídas', short_name = 'Bers./Mídas' WHERE api_football_id = 18474;
UPDATE public.teams SET name = 'BN Norðfjörður', short_name = 'BN' WHERE api_football_id = 18475;
UPDATE public.teams SET name = 'Hafnir', short_name = 'Hafnir' WHERE api_football_id = 18476;
UPDATE public.teams SET name = 'KFK Kópavogur', short_name = 'KFK' WHERE api_football_id = 18477;
UPDATE public.teams SET name = 'Spyrnir', short_name = 'Spyrnir' WHERE api_football_id = 18478;
UPDATE public.teams SET name = 'Þorlákur', short_name = 'Þorlákur' WHERE api_football_id = 22959;
UPDATE public.teams SET name = 'Fjarðabyggð/Höttur/Leiknir', short_name = 'Fjarðab./H/L' WHERE api_football_id = 25517;
UPDATE public.teams SET name = 'BF 108', short_name = 'BF 108' WHERE api_football_id = 25566;
UPDATE public.teams SET name = 'Fálkar', short_name = 'Fálkar' WHERE api_football_id = 25567;
UPDATE public.teams SET name = 'Neisti Dalvík', short_name = 'Neisti D' WHERE api_football_id = 25568;
UPDATE public.grounds SET name = 'Kaplakriki' WHERE notes LIKE '%api_football_venue_id: 821%';
UPDATE public.grounds SET name = 'Valsvöllur' WHERE notes LIKE '%api_football_venue_id: 830%';
UPDATE public.grounds SET name = 'Lambhagavöllur' WHERE notes LIKE '%api_football_venue_id: 2319%';
UPDATE public.grounds SET name = 'Kerecisvöllurinn' WHERE notes LIKE '%api_football_venue_id: 3180%';
UPDATE public.grounds SET name = 'Varmárvöllur' WHERE notes LIKE '%api_football_venue_id: 20543%';
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/822.png' WHERE notes LIKE '%api_football_venue_id: 822%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/826.png' WHERE notes LIKE '%api_football_venue_id: 826%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/19615.png' WHERE notes LIKE '%api_football_venue_id: 19615%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/821.png' WHERE notes LIKE '%api_football_venue_id: 821%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/10591.png' WHERE notes LIKE '%api_football_venue_id: 10591%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/827.png' WHERE notes LIKE '%api_football_venue_id: 827%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/1956.png' WHERE notes LIKE '%api_football_venue_id: 1956%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/830.png' WHERE notes LIKE '%api_football_venue_id: 830%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/829.png' WHERE notes LIKE '%api_football_venue_id: 829%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/820.png' WHERE notes LIKE '%api_football_venue_id: 820%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/823.png' WHERE notes LIKE '%api_football_venue_id: 823%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/831.png' WHERE notes LIKE '%api_football_venue_id: 831%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/825.png' WHERE notes LIKE '%api_football_venue_id: 825%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/2313.png' WHERE notes LIKE '%api_football_venue_id: 2313%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/2318.png' WHERE notes LIKE '%api_football_venue_id: 2318%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/20549.png' WHERE notes LIKE '%api_football_venue_id: 20549%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/2748.png' WHERE notes LIKE '%api_football_venue_id: 2748%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/824.png' WHERE notes LIKE '%api_football_venue_id: 824%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/2320.png' WHERE notes LIKE '%api_football_venue_id: 2320%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/2321.png' WHERE notes LIKE '%api_football_venue_id: 2321%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/20542.png' WHERE notes LIKE '%api_football_venue_id: 20542%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = '/grounds/2319.jpg' WHERE notes LIKE '%api_football_venue_id: 2319%';
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/21596.png' WHERE notes LIKE '%api_football_venue_id: 21596%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = '/grounds/2747.jpg' WHERE notes LIKE '%api_football_venue_id: 2747%';
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/2314.png' WHERE notes LIKE '%api_football_venue_id: 2314%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/2322.png' WHERE notes LIKE '%api_football_venue_id: 2322%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/2317.png' WHERE notes LIKE '%api_football_venue_id: 2317%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/21597.png' WHERE notes LIKE '%api_football_venue_id: 21597%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = '/grounds/20543.jpg' WHERE notes LIKE '%api_football_venue_id: 20543%';
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/3178.png' WHERE notes LIKE '%api_football_venue_id: 3178%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/20544.png' WHERE notes LIKE '%api_football_venue_id: 20544%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/3180.png' WHERE notes LIKE '%api_football_venue_id: 3180%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/21598.png' WHERE notes LIKE '%api_football_venue_id: 21598%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = '/grounds/21599.jpg' WHERE notes LIKE '%api_football_venue_id: 21599%';
UPDATE public.grounds SET image_url = '/grounds/3183.jpg' WHERE notes LIKE '%api_football_venue_id: 3183%';
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/3184.png' WHERE notes LIKE '%api_football_venue_id: 3184%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = '/grounds/3185.jpg' WHERE notes LIKE '%api_football_venue_id: 3185%';
UPDATE public.grounds SET image_url = '/grounds/3186.jpg' WHERE notes LIKE '%api_football_venue_id: 3186%';
UPDATE public.grounds SET image_url = '/grounds/3187.jpg' WHERE notes LIKE '%api_football_venue_id: 3187%';
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/20545.png' WHERE notes LIKE '%api_football_venue_id: 20545%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/4519.png' WHERE notes LIKE '%api_football_venue_id: 4519%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/4520.png' WHERE notes LIKE '%api_football_venue_id: 4520%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/4521.png' WHERE notes LIKE '%api_football_venue_id: 4521%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/20546.png' WHERE notes LIKE '%api_football_venue_id: 20546%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/4524.png' WHERE notes LIKE '%api_football_venue_id: 4524%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/4525.png' WHERE notes LIKE '%api_football_venue_id: 4525%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/20547.png' WHERE notes LIKE '%api_football_venue_id: 20547%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/4527.png' WHERE notes LIKE '%api_football_venue_id: 4527%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/20548.png' WHERE notes LIKE '%api_football_venue_id: 20548%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/4529.png' WHERE notes LIKE '%api_football_venue_id: 4529%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/4530.png' WHERE notes LIKE '%api_football_venue_id: 4530%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/4531.png' WHERE notes LIKE '%api_football_venue_id: 4531%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/4532.png' WHERE notes LIKE '%api_football_venue_id: 4532%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/4522.png' WHERE notes LIKE '%api_football_venue_id: 4522%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/20550.png' WHERE notes LIKE '%api_football_venue_id: 20550%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/11562.png' WHERE notes LIKE '%api_football_venue_id: 11562%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/4534.png' WHERE notes LIKE '%api_football_venue_id: 4534%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/4535.png' WHERE notes LIKE '%api_football_venue_id: 4535%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/4533.png' WHERE notes LIKE '%api_football_venue_id: 4533%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/9799.png' WHERE notes LIKE '%api_football_venue_id: 9799%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/7123.png' WHERE notes LIKE '%api_football_venue_id: 7123%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/18455.png' WHERE notes LIKE '%api_football_venue_id: 18455%' AND image_url IS NULL;
