-- Name overrides for live DB
UPDATE public.teams SET name = 'Ægir', short_name = 'Ægir' WHERE id = 1;
UPDATE public.teams SET name = 'Afríka', short_name = 'Afríka' WHERE id = 2;
UPDATE public.teams SET name = 'Afturelding', short_name = 'Afturelding' WHERE id = 3;
UPDATE public.teams SET name = 'Álafoss', short_name = 'Álafoss' WHERE id = 5;
UPDATE public.teams SET name = 'Álftanes', short_name = 'Álftanes' WHERE id = 6;
UPDATE public.teams SET name = 'Árborg', short_name = 'Árborg' WHERE id = 8;
UPDATE public.teams SET name = 'Augnablik', short_name = 'Augnablik' WHERE id = 9;
UPDATE public.teams SET name = 'Berserkir', short_name = 'Berserkir' WHERE id = 10;
UPDATE public.teams SET name = 'Berserkir/Mídas', short_name = 'Bers./Mídas' WHERE id = 11;
UPDATE public.teams SET name = 'BF 108', short_name = 'BF 108' WHERE id = 12;
UPDATE public.teams SET name = 'Björninn', short_name = 'Björninn' WHERE id = 13;
UPDATE public.teams SET name = 'Blix', short_name = 'Blix' WHERE id = 14;
UPDATE public.teams SET name = 'BN Norðfjörður', short_name = 'BN' WHERE id = 15;
UPDATE public.teams SET name = 'Breiðablik', short_name = 'Breiðablik' WHERE id = 16;
UPDATE public.teams SET name = 'Dalvík/Reynir', short_name = 'Dalvík/R' WHERE id = 18;
UPDATE public.teams SET name = 'Einherji', short_name = 'Einherji' WHERE id = 19;
UPDATE public.teams SET name = 'Elliði', short_name = 'Elliði' WHERE id = 20;
UPDATE public.teams SET name = 'Fálkar', short_name = 'Fálkar' WHERE id = 21;
UPDATE public.teams SET name = 'FH Hafnarfjörður', short_name = 'FH' WHERE id = 22;
UPDATE public.teams SET name = 'Fjarðabyggð/Höttur/Leiknir', short_name = 'Fjarðab./H/L' WHERE id = 24;
UPDATE public.teams SET name = 'Fjarðabyggð', short_name = 'Fjarðabyggð' WHERE id = 25;
UPDATE public.teams SET name = 'Fjarðabyggð/Leiknir', short_name = 'Fjarðab./L' WHERE id = 26;
UPDATE public.teams SET name = 'Fjölnir', short_name = 'Fjölnir' WHERE id = 27;
UPDATE public.teams SET name = 'Fram Reykjavík', short_name = 'Fram' WHERE id = 28;
UPDATE public.teams SET name = 'Fylkir', short_name = 'Fylkir' WHERE id = 30;
UPDATE public.teams SET name = 'GG', short_name = 'GG' WHERE id = 32;
UPDATE public.teams SET name = 'Grindavík', short_name = 'Grindavík' WHERE id = 33;
UPDATE public.teams SET name = 'Grótta', short_name = 'Grótta' WHERE id = 34;
UPDATE public.teams SET name = 'Gullfálkinn', short_name = 'Gullfálkinn' WHERE id = 35;
UPDATE public.teams SET name = 'Hafnir', short_name = 'Hafnir' WHERE id = 36;
UPDATE public.teams SET name = 'Hamar', short_name = 'Hamar' WHERE id = 37;
UPDATE public.teams SET name = 'Hamrarnir', short_name = 'Hamrarnir' WHERE id = 38;
UPDATE public.teams SET name = 'Haukar', short_name = 'Haukar' WHERE id = 39;
UPDATE public.teams SET name = 'HK Kópavogur', short_name = 'HK' WHERE id = 40;
UPDATE public.teams SET name = 'Hörður Ísafjörður', short_name = 'Hörður Í' WHERE id = 41;
UPDATE public.teams SET name = 'Höttur/Huginn', short_name = 'Höttur/H' WHERE id = 42;
UPDATE public.teams SET name = 'Hvíti riddarinn', short_name = 'Hvíti r.' WHERE id = 43;
UPDATE public.teams SET name = 'ÍA Akranes', short_name = 'ÍA' WHERE id = 44;
UPDATE public.teams SET name = 'ÍBU', short_name = 'ÍBU' WHERE id = 45;
UPDATE public.teams SET name = 'ÍBV Vestmannaeyjar', short_name = 'ÍBV' WHERE id = 46;
UPDATE public.teams SET name = 'ÍH', short_name = 'ÍH' WHERE id = 48;
UPDATE public.teams SET name = 'ÍR Reykjavík', short_name = 'ÍR' WHERE id = 49;
UPDATE public.teams SET name = 'Ísbjörninn', short_name = 'Ísbjörninn' WHERE id = 50;
UPDATE public.teams SET name = 'KA Akureyri', short_name = 'KA' WHERE id = 51;
UPDATE public.teams SET name = 'KÁ Hafnarfjörður', short_name = 'KÁ' WHERE id = 52;
UPDATE public.teams SET name = 'Kári', short_name = 'Kári' WHERE id = 53;
UPDATE public.teams SET name = 'KB', short_name = 'KB' WHERE id = 54;
UPDATE public.teams SET name = 'Keflavík', short_name = 'Keflavík' WHERE id = 55;
UPDATE public.teams SET name = 'KF Fjarðabyggð', short_name = 'KF' WHERE id = 57;
UPDATE public.teams SET name = 'KFB', short_name = 'KFB' WHERE id = 58;
UPDATE public.teams SET name = 'KFG Garðabær', short_name = 'KFG' WHERE id = 59;
UPDATE public.teams SET name = 'KFK Kópavogur', short_name = 'KFK' WHERE id = 60;
UPDATE public.teams SET name = 'KFR', short_name = 'KFR' WHERE id = 61;
UPDATE public.teams SET name = 'KFS', short_name = 'KFS' WHERE id = 62;
UPDATE public.teams SET name = 'KH', short_name = 'KH' WHERE id = 63;
UPDATE public.teams SET name = 'KM', short_name = 'KM' WHERE id = 64;
UPDATE public.teams SET name = 'Kórdrengir', short_name = 'Kórdrengir' WHERE id = 65;
UPDATE public.teams SET name = 'Kormákur/Hvöt', short_name = 'Kormákur' WHERE id = 66;
UPDATE public.teams SET name = 'KR Reykjavík', short_name = 'KR' WHERE id = 67;
UPDATE public.teams SET name = 'Kría', short_name = 'Kría' WHERE id = 69;
UPDATE public.teams SET name = 'Leiknir Fljótsdalshérað', short_name = 'Leiknir F' WHERE id = 71;
UPDATE public.teams SET name = 'Leiknir Reykjavík', short_name = 'Leiknir R' WHERE id = 72;
UPDATE public.teams SET name = 'Léttir', short_name = 'Léttir' WHERE id = 73;
UPDATE public.teams SET name = 'Magni', short_name = 'Magni' WHERE id = 74;
UPDATE public.teams SET name = 'Mídas', short_name = 'Mídas' WHERE id = 75;
UPDATE public.teams SET name = 'Neisti Dalvík', short_name = 'Neisti D' WHERE id = 76;
UPDATE public.teams SET name = 'Njarðvík', short_name = 'Njarðvík' WHERE id = 77;
UPDATE public.teams SET name = 'Nökkvi', short_name = 'Nökkvi' WHERE id = 78;
UPDATE public.teams SET name = 'RB', short_name = 'RB' WHERE id = 79;
UPDATE public.teams SET name = 'Reynir Sandgerði', short_name = 'Reynir S' WHERE id = 80;
UPDATE public.teams SET name = 'Reynir Hellissandur', short_name = 'Reynir H' WHERE id = 81;
UPDATE public.teams SET name = 'Samherjar', short_name = 'Samherjar' WHERE id = 82;
UPDATE public.teams SET name = 'Selfoss', short_name = 'Selfoss' WHERE id = 83;
UPDATE public.teams SET name = 'Sindri', short_name = 'Sindri' WHERE id = 85;
UPDATE public.teams SET name = 'Skallagrímur', short_name = 'Skallagrímur' WHERE id = 86;
UPDATE public.teams SET name = 'Skandinavía', short_name = 'Skandinavía' WHERE id = 87;
UPDATE public.teams SET name = 'Snæfell', short_name = 'Snæfell' WHERE id = 88;
UPDATE public.teams SET name = 'Spyrnir', short_name = 'Spyrnir' WHERE id = 89;
UPDATE public.teams SET name = 'SR', short_name = 'SR' WHERE id = 90;
UPDATE public.teams SET name = 'Stjarnan', short_name = 'Stjarnan' WHERE id = 91;
UPDATE public.teams SET name = 'Stokkseyri', short_name = 'Stokkseyri' WHERE id = 93;
UPDATE public.teams SET name = 'Þór Akureyri', short_name = 'Þór' WHERE id = 95;
UPDATE public.teams SET name = 'Þorlákur', short_name = 'Þorlákur' WHERE id = 96;
UPDATE public.teams SET name = 'Þróttur Reykjavík', short_name = 'Þróttur R' WHERE id = 97;
UPDATE public.teams SET name = 'Þróttur Vogar', short_name = 'Þróttur V' WHERE id = 99;
UPDATE public.teams SET name = 'Tindastóll', short_name = 'Tindastóll' WHERE id = 100;
UPDATE public.teams SET name = 'Úlfarnir', short_name = 'Úlfarnir' WHERE id = 102;
UPDATE public.teams SET name = 'Vængir Júpíters', short_name = 'Vængir J' WHERE id = 103;
UPDATE public.teams SET name = 'Valur', short_name = 'Valur' WHERE id = 104;
UPDATE public.teams SET name = 'Vatnaliljur', short_name = 'Vatnaliljur' WHERE id = 106;
UPDATE public.teams SET name = 'Vestri', short_name = 'Vestri' WHERE id = 107;
UPDATE public.teams SET name = 'Víðir', short_name = 'Víðir' WHERE id = 108;
UPDATE public.teams SET name = 'Víkingur Ólafsvík', short_name = 'Víkingur Ó' WHERE id = 109;
UPDATE public.teams SET name = 'Víkingur Reykjavík', short_name = 'Víkingur R' WHERE id = 110;
UPDATE public.teams SET name = 'Völsungur', short_name = 'Völsungur' WHERE id = 112;
UPDATE public.teams SET name = 'Ýmir', short_name = 'Ýmir' WHERE id = 113;
UPDATE public.grounds SET name = 'Kaplakriki' WHERE notes LIKE '%api_football_venue_id: 821%';
UPDATE public.grounds SET name = 'Valsvöllur' WHERE notes LIKE '%api_football_venue_id: 830%';
UPDATE public.grounds SET name = 'Lambhagavöllur' WHERE notes LIKE '%api_football_venue_id: 2319%';
UPDATE public.grounds SET name = 'Kerecisvöllurinn' WHERE notes LIKE '%api_football_venue_id: 3180%';
UPDATE public.grounds SET name = 'Varmárvöllur' WHERE notes LIKE '%api_football_venue_id: 20543%';
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/822.png' WHERE notes LIKE '%api_football_venue_id: 822%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/826.png' WHERE notes LIKE '%api_football_venue_id: 826%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/19615.png' WHERE notes LIKE '%api_football_venue_id: 19615%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/821.png' WHERE notes LIKE '%api_football_venue_id: 821%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/10591.png' WHERE notes LIKE '%api_football_venue_id: 10591%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/827.png' WHERE notes LIKE '%api_football_venue_id: 827%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/1956.png' WHERE notes LIKE '%api_football_venue_id: 1956%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/830.png' WHERE notes LIKE '%api_football_venue_id: 830%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/829.png' WHERE notes LIKE '%api_football_venue_id: 829%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/820.png' WHERE notes LIKE '%api_football_venue_id: 820%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/823.png' WHERE notes LIKE '%api_football_venue_id: 823%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/831.png' WHERE notes LIKE '%api_football_venue_id: 831%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/825.png' WHERE notes LIKE '%api_football_venue_id: 825%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/2313.png' WHERE notes LIKE '%api_football_venue_id: 2313%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/2318.png' WHERE notes LIKE '%api_football_venue_id: 2318%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/20549.png' WHERE notes LIKE '%api_football_venue_id: 20549%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/2748.png' WHERE notes LIKE '%api_football_venue_id: 2748%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/824.png' WHERE notes LIKE '%api_football_venue_id: 824%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/2320.png' WHERE notes LIKE '%api_football_venue_id: 2320%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/2321.png' WHERE notes LIKE '%api_football_venue_id: 2321%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/20542.png' WHERE notes LIKE '%api_football_venue_id: 20542%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = '/grounds/2319.jpg' WHERE notes LIKE '%api_football_venue_id: 2319%';
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/21596.png' WHERE notes LIKE '%api_football_venue_id: 21596%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = '/grounds/2747.jpg' WHERE notes LIKE '%api_football_venue_id: 2747%';
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/2314.png' WHERE notes LIKE '%api_football_venue_id: 2314%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/2322.png' WHERE notes LIKE '%api_football_venue_id: 2322%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/2317.png' WHERE notes LIKE '%api_football_venue_id: 2317%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/21597.png' WHERE notes LIKE '%api_football_venue_id: 21597%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = '/grounds/20543.jpg' WHERE notes LIKE '%api_football_venue_id: 20543%';
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/3178.png' WHERE notes LIKE '%api_football_venue_id: 3178%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/20544.png' WHERE notes LIKE '%api_football_venue_id: 20544%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/3180.png' WHERE notes LIKE '%api_football_venue_id: 3180%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/21598.png' WHERE notes LIKE '%api_football_venue_id: 21598%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = '/grounds/21599.jpg' WHERE notes LIKE '%api_football_venue_id: 21599%';
UPDATE public.grounds SET image_url = '/grounds/3183.jpg' WHERE notes LIKE '%api_football_venue_id: 3183%';
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/3184.png' WHERE notes LIKE '%api_football_venue_id: 3184%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = '/grounds/3185.jpg' WHERE notes LIKE '%api_football_venue_id: 3185%';
UPDATE public.grounds SET image_url = '/grounds/3186.jpg' WHERE notes LIKE '%api_football_venue_id: 3186%';
UPDATE public.grounds SET image_url = '/grounds/3187.jpg' WHERE notes LIKE '%api_football_venue_id: 3187%';
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/20545.png' WHERE notes LIKE '%api_football_venue_id: 20545%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/4519.png' WHERE notes LIKE '%api_football_venue_id: 4519%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/4520.png' WHERE notes LIKE '%api_football_venue_id: 4520%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/4521.png' WHERE notes LIKE '%api_football_venue_id: 4521%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/20546.png' WHERE notes LIKE '%api_football_venue_id: 20546%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/4524.png' WHERE notes LIKE '%api_football_venue_id: 4524%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/4525.png' WHERE notes LIKE '%api_football_venue_id: 4525%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/20547.png' WHERE notes LIKE '%api_football_venue_id: 20547%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/4527.png' WHERE notes LIKE '%api_football_venue_id: 4527%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/20548.png' WHERE notes LIKE '%api_football_venue_id: 20548%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/4529.png' WHERE notes LIKE '%api_football_venue_id: 4529%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/4530.png' WHERE notes LIKE '%api_football_venue_id: 4530%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/4531.png' WHERE notes LIKE '%api_football_venue_id: 4531%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/4532.png' WHERE notes LIKE '%api_football_venue_id: 4532%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/4522.png' WHERE notes LIKE '%api_football_venue_id: 4522%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/20550.png' WHERE notes LIKE '%api_football_venue_id: 20550%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/11562.png' WHERE notes LIKE '%api_football_venue_id: 11562%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/4534.png' WHERE notes LIKE '%api_football_venue_id: 4534%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/4535.png' WHERE notes LIKE '%api_football_venue_id: 4535%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/4533.png' WHERE notes LIKE '%api_football_venue_id: 4533%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/9799.png' WHERE notes LIKE '%api_football_venue_id: 9799%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/7123.png' WHERE notes LIKE '%api_football_venue_id: 7123%' AND image_url IS NULL;
UPDATE public.grounds SET image_url = 'https://media.api-sports.io/football/venues/18455.png' WHERE notes LIKE '%api_football_venue_id: 18455%' AND image_url IS NULL;
UPDATE public.fixtures SET opponent_name = 'Ægir' WHERE opponent_name = 'Ægir';
UPDATE public.fixtures SET opponent_name = 'Afríka' WHERE opponent_name = 'Afríka';
UPDATE public.fixtures SET opponent_name = 'Afturelding' WHERE opponent_name = 'Afturelding';
UPDATE public.fixtures SET opponent_name = 'Álafoss' WHERE opponent_name = 'Álafoss';
UPDATE public.fixtures SET opponent_name = 'Álftanes' WHERE opponent_name = 'Álftanes';
UPDATE public.fixtures SET opponent_name = 'Árborg' WHERE opponent_name = 'Árborg';
UPDATE public.fixtures SET opponent_name = 'Augnablik' WHERE opponent_name = 'Augnablik';
UPDATE public.fixtures SET opponent_name = 'Berserkir' WHERE opponent_name = 'Berserkir';
UPDATE public.fixtures SET opponent_name = 'Berserkir/Mídas' WHERE opponent_name = 'Berserkir / Mídas';
UPDATE public.fixtures SET opponent_name = 'BF 108' WHERE opponent_name = 'BF 108';
UPDATE public.fixtures SET opponent_name = 'Björninn' WHERE opponent_name = 'Björninn';
UPDATE public.fixtures SET opponent_name = 'Blix' WHERE opponent_name = 'Blix';
UPDATE public.fixtures SET opponent_name = 'BN Norðfjörður' WHERE opponent_name = 'Boltafélag Norðfjarðar';
UPDATE public.fixtures SET opponent_name = 'Breiðablik' WHERE opponent_name = 'Breidablik';
UPDATE public.fixtures SET opponent_name = 'Dalvík/Reynir' WHERE opponent_name = 'Dalvík / Reynir';
UPDATE public.fixtures SET opponent_name = 'Einherji' WHERE opponent_name = 'Einherji';
UPDATE public.fixtures SET opponent_name = 'Elliði' WHERE opponent_name = 'Ellidi';
UPDATE public.fixtures SET opponent_name = 'Fálkar' WHERE opponent_name = 'Fálkar';
UPDATE public.fixtures SET opponent_name = 'FH Hafnarfjörður' WHERE opponent_name = 'FH hafnarfjordur';
UPDATE public.fixtures SET opponent_name = 'Fjarðabyggð/Höttur/Leiknir' WHERE opponent_name = 'Fjard / Hött / Leiknir';
UPDATE public.fixtures SET opponent_name = 'Fjarðabyggð' WHERE opponent_name = 'Fjardabyggd';
UPDATE public.fixtures SET opponent_name = 'Fjarðabyggð/Leiknir' WHERE opponent_name = 'Fjardabyggd / Leiknir';
UPDATE public.fixtures SET opponent_name = 'Fjölnir' WHERE opponent_name = 'Fjolnir';
UPDATE public.fixtures SET opponent_name = 'Fram Reykjavík' WHERE opponent_name = 'Fram Reykjavik';
UPDATE public.fixtures SET opponent_name = 'Fylkir' WHERE opponent_name = 'Fylkir';
UPDATE public.fixtures SET opponent_name = 'GG' WHERE opponent_name = 'GG';
UPDATE public.fixtures SET opponent_name = 'Grindavík' WHERE opponent_name = 'Grindavik';
UPDATE public.fixtures SET opponent_name = 'Grótta' WHERE opponent_name = 'Grotta';
UPDATE public.fixtures SET opponent_name = 'Gullfálkinn' WHERE opponent_name = 'Gullfálkinn';
UPDATE public.fixtures SET opponent_name = 'Hafnir' WHERE opponent_name = 'Hafnir';
UPDATE public.fixtures SET opponent_name = 'Hamar' WHERE opponent_name = 'Hamar';
UPDATE public.fixtures SET opponent_name = 'Hamrarnir' WHERE opponent_name = 'Hamrarnir';
UPDATE public.fixtures SET opponent_name = 'Haukar' WHERE opponent_name = 'Haukar';
UPDATE public.fixtures SET opponent_name = 'HK Kópavogur' WHERE opponent_name = 'HK Kopavogur';
UPDATE public.fixtures SET opponent_name = 'Hörður Ísafjörður' WHERE opponent_name = 'Hörður Í.';
UPDATE public.fixtures SET opponent_name = 'Höttur/Huginn' WHERE opponent_name = 'Höttur / Huginn';
UPDATE public.fixtures SET opponent_name = 'Hvíti riddarinn' WHERE opponent_name = 'Hvíti riddarinn';
UPDATE public.fixtures SET opponent_name = 'ÍA Akranes' WHERE opponent_name = 'IA Akranes';
UPDATE public.fixtures SET opponent_name = 'ÍBU' WHERE opponent_name = 'ÍBU';
UPDATE public.fixtures SET opponent_name = 'ÍBV Vestmannaeyjar' WHERE opponent_name = 'IBV Vestmannaeyjar';
UPDATE public.fixtures SET opponent_name = 'ÍH' WHERE opponent_name = 'ÍH';
UPDATE public.fixtures SET opponent_name = 'ÍR Reykjavík' WHERE opponent_name = 'IR Reykjavik';
UPDATE public.fixtures SET opponent_name = 'Ísbjörninn' WHERE opponent_name = 'Ísbjörninn';
UPDATE public.fixtures SET opponent_name = 'KA Akureyri' WHERE opponent_name = 'KA Akureyri';
UPDATE public.fixtures SET opponent_name = 'KÁ Hafnarfjörður' WHERE opponent_name = 'KÁ Hafnarfjördur';
UPDATE public.fixtures SET opponent_name = 'Kári' WHERE opponent_name = 'Kári';
UPDATE public.fixtures SET opponent_name = 'KB' WHERE opponent_name = 'KB';
UPDATE public.fixtures SET opponent_name = 'Keflavík' WHERE opponent_name = 'Keflavik';
UPDATE public.fixtures SET opponent_name = 'KF Fjarðabyggð' WHERE opponent_name = 'KF';
UPDATE public.fixtures SET opponent_name = 'KFB' WHERE opponent_name = 'KFB';
UPDATE public.fixtures SET opponent_name = 'KFG Garðabær' WHERE opponent_name = 'KFG';
UPDATE public.fixtures SET opponent_name = 'KFK Kópavogur' WHERE opponent_name = 'KFK Kópavogur';
UPDATE public.fixtures SET opponent_name = 'KFR' WHERE opponent_name = 'KFR';
UPDATE public.fixtures SET opponent_name = 'KFS' WHERE opponent_name = 'KFS';
UPDATE public.fixtures SET opponent_name = 'KH' WHERE opponent_name = 'KH';
UPDATE public.fixtures SET opponent_name = 'KM' WHERE opponent_name = 'KM';
UPDATE public.fixtures SET opponent_name = 'Kórdrengir' WHERE opponent_name = 'Kórdrengir';
UPDATE public.fixtures SET opponent_name = 'Kormákur/Hvöt' WHERE opponent_name = 'Kormákur / Hvöt';
UPDATE public.fixtures SET opponent_name = 'KR Reykjavík' WHERE opponent_name = 'KR Reykjavik';
UPDATE public.fixtures SET opponent_name = 'Kría' WHERE opponent_name = 'Kría';
UPDATE public.fixtures SET opponent_name = 'Leiknir Fljótsdalshérað' WHERE opponent_name = 'Leiknir F.';
UPDATE public.fixtures SET opponent_name = 'Leiknir Reykjavík' WHERE opponent_name = 'Leiknir R.';
UPDATE public.fixtures SET opponent_name = 'Léttir' WHERE opponent_name = 'Léttir';
UPDATE public.fixtures SET opponent_name = 'Magni' WHERE opponent_name = 'Magni';
UPDATE public.fixtures SET opponent_name = 'Mídas' WHERE opponent_name = 'Mídas';
UPDATE public.fixtures SET opponent_name = 'Neisti Dalvík' WHERE opponent_name = 'Neisti D.';
UPDATE public.fixtures SET opponent_name = 'Njarðvík' WHERE opponent_name = 'Njardvik';
UPDATE public.fixtures SET opponent_name = 'Nökkvi' WHERE opponent_name = 'Nökkvi';
UPDATE public.fixtures SET opponent_name = 'RB' WHERE opponent_name = 'RB';
UPDATE public.fixtures SET opponent_name = 'Reynir Sandgerði' WHERE opponent_name = 'Reynir';
UPDATE public.fixtures SET opponent_name = 'Reynir Hellissandur' WHERE opponent_name = 'Reynir Hellissandur';
UPDATE public.fixtures SET opponent_name = 'Samherjar' WHERE opponent_name = 'Samherjar';
UPDATE public.fixtures SET opponent_name = 'Selfoss' WHERE opponent_name = 'Selfoss';
UPDATE public.fixtures SET opponent_name = 'Sindri' WHERE opponent_name = 'Sindri';
UPDATE public.fixtures SET opponent_name = 'Skallagrímur' WHERE opponent_name = 'Skallagrímur';
UPDATE public.fixtures SET opponent_name = 'Skandinavía' WHERE opponent_name = 'Skandinavía';
UPDATE public.fixtures SET opponent_name = 'Snæfell' WHERE opponent_name = 'Snæfell';
UPDATE public.fixtures SET opponent_name = 'Spyrnir' WHERE opponent_name = 'Spyrnir';
UPDATE public.fixtures SET opponent_name = 'SR' WHERE opponent_name = 'SR';
UPDATE public.fixtures SET opponent_name = 'Stjarnan' WHERE opponent_name = 'Stjarnan';
UPDATE public.fixtures SET opponent_name = 'Stokkseyri' WHERE opponent_name = 'Stokkseyri';
UPDATE public.fixtures SET opponent_name = 'Þór Akureyri' WHERE opponent_name = 'Thor Akureyri';
UPDATE public.fixtures SET opponent_name = 'Þorlákur' WHERE opponent_name = 'Thorlákur';
UPDATE public.fixtures SET opponent_name = 'Þróttur Reykjavík' WHERE opponent_name = 'Throttur Reykjavik';
UPDATE public.fixtures SET opponent_name = 'Þróttur Vogar' WHERE opponent_name = 'Thróttur Vogar';
UPDATE public.fixtures SET opponent_name = 'Tindastóll' WHERE opponent_name = 'Tindastóll';
UPDATE public.fixtures SET opponent_name = 'Úlfarnir' WHERE opponent_name = 'Úlfarnir';
UPDATE public.fixtures SET opponent_name = 'Vængir Júpíters' WHERE opponent_name = 'Vængir Júpiters';
UPDATE public.fixtures SET opponent_name = 'Valur' WHERE opponent_name = 'Valur Reykjavik';
UPDATE public.fixtures SET opponent_name = 'Vatnaliljur' WHERE opponent_name = 'Vatnaliljur';
UPDATE public.fixtures SET opponent_name = 'Vestri' WHERE opponent_name = 'Vestri';
UPDATE public.fixtures SET opponent_name = 'Víðir' WHERE opponent_name = 'Vídir';
UPDATE public.fixtures SET opponent_name = 'Víkingur Ólafsvík' WHERE opponent_name = 'Vikingur Olafsiik';
UPDATE public.fixtures SET opponent_name = 'Víkingur Reykjavík' WHERE opponent_name = 'Vikingur Reykjavik';
UPDATE public.fixtures SET opponent_name = 'Völsungur' WHERE opponent_name = 'Völsungur';
UPDATE public.fixtures SET opponent_name = 'Ýmir' WHERE opponent_name = 'Ýmir';
